{
	"version": 1711297885,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/spritefont.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/tilemap.png",
		"images/sprite8-sheet0.png",
		"images/particles.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/particles2.png",
		"images/sprite15-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"media/level-up-bonus-sequence-3-186892.ogg",
		"media/coin.m4a",
		"media/coin.ogg",
		"media/tick.m4a",
		"media/tick.ogg",
		"media/spin.m4a",
		"media/spin.ogg",
		"media/double down - sonic lost world [ost].m4a",
		"media/double down - sonic lost world [ost].ogg",
		"media/playful-casino-slot-machine-jackpot-3-183921.m4a",
		"media/playful-casino-slot-machine-jackpot-3-183921.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"penumbra.png"
	]
}